#pragma once

#define ERR_NOSUCHNICK 401
#define ERR_NOSUCHSERVER 402
#define ERR_NOSUCHCHANNEL 403
#define ERR_CANNOTSENDTOCHAN 404

#define ERR_NORECIPIENT 411
#define ERR_NOTEXTTOSEND 412
#define ERR_NOTOPLEVEL 413
#define ERR_WILDTOPLEVEL 414

#define ERR_NONICKNAMEGIVEN 431
#define ERR_ERRONEUSNICKNAM 432
#define ERR_NICKNAMEINUSE 433
#define ERR_NICKCOLLISION 436

#define ERR_NOTONCHANNEL 442

#define ERR_NEEDMOREPARAMS 461
#define ERR_ALREADYREGISTRED 462

#define ERR_PASSWDMISMATCH 464
#define ERR_YOUREBANNEDCREEP 465

#define ERR_CHANNELISFULL 471
#define ERR_INVITEONLYCHAN 473
#define ERR_BANNEDFROMCHAN 474
#define ERR_BADCHANNELKEY 475
#define ERR_BADCHANMASK 476
#define ERR_TOOMANYCHANNELS 477

#define ERR_CHANOPRIVSNEEDED 482
